@baseUrl = http://localhost:8080/recipes-v2/

# create new recipe
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Ham and toast",
  "ingredients": [
    {
      "name": "bread",
      "amount": 6
    },{
      "name": "ham",
      "amount": 6
    },{
      "name": "toast",
      "amount": 6
    }
  ]
}

### create new recipe
PUT {{baseUrl}}
Content-Type: application/json

{
  "id": 2,
  "name": "Ham and sausage",
  "ingredients": [
    {
      "name": "bread",
      "amount": 1
    },{
      "name": "ham",
      "amount": 2
    },{
      "name": "sausage",
      "amount": 3
    }
  ]
}
###
GET {{baseUrl}}2

###
GET {{baseUrl}}ham-and-cheese-toasties

###
GET {{baseUrl}}ham-and-butter