@baseUrl = http://localhost:8080/recipes-v2/

# create new recipe
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Ham and toast",
  "ingredients": [
    {
      "name": "bread",
      "amount": 9
    },{
      "name": "ham",
      "amount": 9
    },{
      "name": "toast",
      "amount": 9
    }
  ]
}
###
GET {{baseUrl}}2

###
GET {{baseUrl}}ham-and-cheese-toasties

###
GET {{baseUrl}}ham-and-butter